version: '3.8'

services:
  webui:
    build: 
      context: .
      dockerfile: ReviewApplication.WebUI/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    environment:
      NODE_ENV: development
    depends_on: 
      - webapi
  
  webapi:
    image: api-dev:latest
    container_name: review-web-api
    build:
      context: .
      dockerfile: ReviewApplication.WebAPI/Dockerfile
    ports:
      - "5005:5005"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:5005;"
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword

  db:
    image: postgres:latest
    container_name: mypostgres
    ports:
      - "9001:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  api-dev:
    driver: bridge